---

- name: Comon configuration
  hosts: all
  become: true
  roles:
    - common

- name: k3s Server configuration
  hosts: HugoS
  become: true
  environment:
        install_k3s_exec: --flannel-backend none --token 12345
  roles:
    - server

- name: k3s Agent configuration
  hosts: HugoSW
  become: true
  roles:
    - server_worker