---

- name: Comon configuration
  hosts: all
  become: true
  roles:
    - common

- name: k3s Server configuration
  hosts: HugoS
  become: true
  roles:
    - server

- name: k3s Agent configuration
  hosts: HugoSW
  become: true
  roles:
    - server_worker